// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7jpDrH6c9ROo9jcttdvX_YK6ysOlf1bw',
    appId: '1:490039520157:web:9f834923ad3a28538fdd74',
    messagingSenderId: '490039520157',
    projectId: 'gardenplanner-d69b4',
    authDomain: 'gardenplanner-d69b4.firebaseapp.com',
    storageBucket: 'gardenplanner-d69b4.appspot.com',
    measurementId: 'G-9PE9DCZ8YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJxNRK-AQnhansw0Lg1BLpgMw1tmqIBu0',
    appId: '1:490039520157:android:6619805300b23fd58fdd74',
    messagingSenderId: '490039520157',
    projectId: 'gardenplanner-d69b4',
    storageBucket: 'gardenplanner-d69b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKTY9MceyAGWvHMoVrjJjd_LHODeWTaZM',
    appId: '1:490039520157:ios:a0d9550cf29a4b2b8fdd74',
    messagingSenderId: '490039520157',
    projectId: 'gardenplanner-d69b4',
    storageBucket: 'gardenplanner-d69b4.appspot.com',
    iosClientId: '490039520157-cunjeulrka10fug3kv7b2h6daf8d1gbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
