version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zorglub
      MONGO_INITDB_DATABASE: garden-planner
    ports:
      - "27017:27017"
    volumes: 
      - type: volume
        source: garden-planner-volume
        target: /data/db
  api:
    build:
      context: ./api
      target: raspberry   # debug, windows ou raspberry
    ports:
      - "8081:8081"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PWD: zorglub
      MONGO_DBNAME: garden-planner
    volumes:
      - type: volume
        source : garden-planner-api-volume
        target: /opt/app/api

  webapp:
    build:
      context: ./app
      target: raspberry   # debug, windows ou raspberry
    ports:
      - "8080:80"
      - "8083:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro  

volumes:
  garden-planner-volume:

  garden-planner-api-volume:
  
