
services:

  api:
    image: garden-planner-api:latest
    ports:
      - "8081:8081"
    environment:
      SQLITE_PATH: /opt/app/api/garden-planner.db
    volumes:
      - type: bind
        source: /share/local/containers-data/garden-planner/api
        target: /opt/app/api
    restart: unless-stopped

  webapp:
    platform: linux/amd64
    image: garden-planner-webapp:latest
    ports:
      - "8083:80"
    depends_on:
      - api
    restart: unless-stopped

  meteo:
    platform: linux/amd64
    image: garden-planner-meteo:latest
    ports:
      - "8082:8082"
    environment:
      SQLITE_PATH: /data/meteo.db
    volumes:
      - type: bind
        source: /share/local/containers-data/garden-planner/meteo
        target: /data
    restart: unless-stopped
