
services:
  api:
    build:
      context: ./api
      target: nas   # debug, windows , nas ou raspberry
    ports:
      - "8081:8081"
    environment:
      SQLITE_PATH: /opt/app/api/garden-planner.db
    volumes:
      - type: bind
        source: /local/containers-data/garden-planner/api
        target: /opt/app/api

  webapp:
    build:
      context: ./app
      target: nas   # debug, windows , nasou raspberry
    ports:
      - "8080:80"
      - "8083:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro

  meteo:
    build:
      context: ./meteo
      target: nas   # debug, windows ou raspberry
    ports:
      - "8082:8082"
    environment:
      SQLITE_PATH: /data/meteo.db
    volumes:
      - type: volume
        source: garden-planner-meteo-volume
        target: /opt/app/meteo
      - type: bind
        source: /local/containers-data/garden-planner/meteo-sqlite
        target: /data

volumes:
  garden-planner-meteo-volume:
    name: "garden-planner-meteo"
